name: Lint

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
  pull_request:
    paths-ignore:
      - "**/*.md"

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
          cache: true
      - name: Install dependencies
        run: go mod tidy
      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          skip-cache: true
          version: latest
          args: --timeout=3m ./...
